name: Quality Metrics & Performance

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # Run weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  code-metrics:
    name: Code Quality Metrics
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install analysis tools
      run: |
        pip install radon complexity
    
    - name: Analyze code complexity
      run: |
        echo "## Code Quality Report - $(date)" > metrics-report.md
        echo "" >> metrics-report.md
        
        echo "### Python Code Metrics" >> metrics-report.md
        echo "" >> metrics-report.md
        
        echo "#### Cyclomatic Complexity" >> metrics-report.md
        cd backend && radon cc . --show-complexity --average >> ../metrics-report.md || true
        cd ..
        echo "" >> metrics-report.md
        
        echo "#### Maintainability Index" >> metrics-report.md
        cd backend && radon mi . >> ../metrics-report.md || true
        cd ..
        echo "" >> metrics-report.md
    
    - name: Upload metrics report
      uses: actions/upload-artifact@v4
      with:
        name: quality-metrics-report
        path: metrics-report.md

  security-scan:
    name: Security Overview
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        output: 'trivy-results.txt'
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-overview
        path: trivy-results.txt
